"""Build project-level BibTeX mirrors under papers/bib."""
from __future__ import annotations

from pathlib import Path
from typing import Any

import frontmatter

from ..core.paths import (
    PAPERS_AI_GENERATED_BIB,
    PAPERS_NOTES_DIR,
    PAPERS_REFERENCES_BIB,
    WRITING_AI_BIB,
    WRITING_BASE,
)


def generate_bibtex(meta: dict[str, Any]) -> str:
    citekey = meta.get("id", "unknown")
    item_type = meta.get("item_type", "")
    is_proceedings = "conference" in item_type.lower() or "proceedings" in item_type.lower()
    bib_type = "inproceedings" if is_proceedings else "article"
    venue_field = "booktitle" if is_proceedings else "journal"

    authors_raw = meta.get("authors", [])

    def fmt(author: str) -> str:
        if "," in author:
            parts = [p.strip() for p in author.split(",", 1)]
            return f"{parts[1]} {parts[0]}" if parts[1] else parts[0]
        return author

    authors_bib = " and ".join(fmt(a) for a in authors_raw)
    lines = [f"@{bib_type}{{{citekey},"]
    lines.append(f"  title     = {{{meta.get('title', '')}}},")
    if authors_bib:
        lines.append(f"  author    = {{{authors_bib}}},")
    if meta.get("year"):
        lines.append(f"  year      = {{{meta['year']}}},")
    if meta.get("venue"):
        lines.append(f"  {venue_field:<9} = {{{meta['venue']}}},")
    if meta.get("doi"):
        lines.append(f"  doi       = {{{meta['doi']}}},")
    if meta.get("arxiv_id"):
        lines.append(f"  eprint    = {{{meta['arxiv_id']}}},")
        lines.append("  archivePrefix = {arXiv},")
    url = (meta.get("links") or {}).get("url", "")
    if url:
        lines.append(f"  url       = {{{url}}},")
    lines.append("}")
    return "\n".join(lines)


def _paper_metas(root: Path) -> list[dict[str, Any]]:
    papers_dir = root / PAPERS_NOTES_DIR
    metas: list[dict[str, Any]] = []
    if not papers_dir.exists():
        return metas
    for md_file in sorted(papers_dir.glob("*.md")):
        try:
            post = frontmatter.load(md_file)
            meta = dict(post.metadata)
            if meta.get("title"):
                metas.append(meta)
        except Exception:
            continue
    return metas


def _collect_ai_bib(root: Path) -> str:
    writing_root = root / WRITING_BASE
    if not writing_root.exists():
        return ""
    chunks: list[str] = []
    for ai_file in sorted(writing_root.glob(f"*/{WRITING_AI_BIB}")):
        text = ai_file.read_text(encoding="utf-8").strip()
        entries = [line for line in text.splitlines() if not line.lstrip().startswith("%")]
        if not "".join(entries).strip():
            continue
        writing_id = ai_file.relative_to(writing_root).parts[0]
        chunks.append(f"% From writing project: {writing_id}\n{text}")
    return "\n\n".join(chunks).strip()


def rebuild_papers_bib_files(root: Path, rebuild_ai: bool = True) -> dict[str, int]:
    """Refresh papers/bib mirrors from paper notes and optionally from writing AI bibs.

    Pass rebuild_ai=False for operations (Zotero sync, paper add/update) that
    don't affect AI-pending entries — preserves ai-generated.bib as-is.
    """
    refs_path = root / PAPERS_REFERENCES_BIB
    ai_path = root / PAPERS_AI_GENERATED_BIB
    refs_path.parent.mkdir(parents=True, exist_ok=True)

    refs = [generate_bibtex(meta) for meta in _paper_metas(root)]
    refs_text = (
        "% papers/bib/references.read_only.bib\n"
        "% Generated by ResearchBuddy from papers/notes/*.md. Do not edit by hand.\n\n"
        + "\n\n".join(refs).strip()
        + "\n"
    )
    refs_path.write_text(refs_text, encoding="utf-8")

    if rebuild_ai:
        ai_text_body = _collect_ai_bib(root)
        ai_text = (
            "% papers/bib/ai-generated.bib\n"
            "% Generated by ResearchBuddy from writing/Project/*/bibs/ai_generated.bib.\n\n"
            + ai_text_body
            + ("\n" if ai_text_body else "")
        )
        ai_path.write_text(ai_text, encoding="utf-8")
        ai_count = ai_text_body.count("@")
    else:
        try:
            existing = ai_path.read_text(encoding="utf-8") if ai_path.exists() else ""
        except OSError:
            existing = ""
        ai_count = existing.count("@")

    return {"references": len(refs), "ai_generated": ai_count}
